version: 0.2

phases:

  build:
    commands:
      - echo build image
      - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 364031579476.dkr.ecr.us-east-2.amazonaws.com
      - docker build -t image .
      - docker tag image:latest 364031579476.dkr.ecr.us-east-2.amazonaws.com/image:latest

  post_build:
    commands:
      - echo Pushing to ECR
      - docker push 364031579476.dkr.ecr.us-east-2.amazonaws.com/image:latest
artifacts:
  files: imagedefinitions.json
